# Generated by Django 5.2.3 on 2025-07-01 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_summary', models.JSONField()),
                ('compliance_summary', models.JSONField()),
                ('emotion', models.CharField(max_length=10)),
                ('compliance_score', models.IntegerField()),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='core.conversation')),
            ],
        ),
    ]
