# Generated by Django 5.2.3 on 2025-07-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_analysisresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotionresult',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='ComplianceResult',
        ),
        migrations.DeleteModel(
            name='EmotionResult',
        ),
    ]
